### ISSUE TITLE
Running error with "__init__.py"

### ISSUE THREAD

**Issue by Handymanalan** [smaegol/PlasFlow#27]
Hi,

I installed PlasFlow through anaconda with the command line:
**conda create -n plasflow python=3.5 plasflow**

Then I ran plasflow.py but then I got the following errors:

Calculating kmer frequencies using kmer 5
Transforming kmer frequencies
Traceback (most recent call last):
  File "/srv/scratch/z3336178/anaconda/envs/plasflow/bin/PlasFlow.py", line 261, in <module>
    vote_proba = vote_class.predict_proba(input_data)
  File "/srv/scratch/z3336178/anaconda/envs/plasflow/bin/PlasFlow.py", line 215, in predict_proba
    self.probas_ = [clf.predict_proba_tf(X) for clf in self.clfs]
  File "/srv/scratch/z3336178/anaconda/envs/plasflow/bin/PlasFlow.py", line 215, in <listcomp>
    self.probas_ = [clf.predict_proba_tf(X) for clf in self.clfs]
  File "/srv/scratch/z3336178/anaconda/envs/plasflow/bin/PlasFlow.py", line 171, in predict_proba_tf
    import tensorflow as tf
  File "/srv/scratch/z3336178/anaconda/envs/plasflow/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/srv/scratch/z3336178/anaconda/envs/plasflow/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/srv/scratch/z3336178/anaconda/envs/plasflow/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/srv/scratch/z3336178/anaconda/envs/plasflow/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: /srv/scratch/z3336178/anaconda/envs/plasflow/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolEb

Is it a compatibility problem? 

Cheers and many thanks

Alan

**Comment by liangjinsong** [comment]
I also encountered the same problem, can anyone figure out the reason?

**Comment by VadimDu** [comment]
I encounter the same error. I have installed PlasFlow as instructed using Conda (Python 3.5 etc').
Any updates regarding this issue?

Thanks
Vadim
