### ISSUE TITLE
Conda install -  ImportError: libicuuc.so.58: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lowandrew** [smaegol/PlasFlow#3]
Hello,

I attempted to install PlasFlow using conda as recommended in your README, but it looks like conda is having some issues with a dependency - when I try to run PlasFlow.py, I get the following ImportError:
```
PlasFlow.py --input /home/lowa/test.fasta --output classified.txt
Traceback (most recent call last):
  File "/home/lowa/miniconda3/envs/plasflow/bin/PlasFlow.py", line 48, in <module>
    from rpy2.robjects.packages import importr
  File "/home/lowa/miniconda3/envs/plasflow/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 15, in <module>
    import rpy2.rinterface as rinterface
  File "/home/lowa/miniconda3/envs/plasflow/lib/python3.5/site-packages/rpy2/rinterface/__init__.py", line 99, in <module>
    from rpy2.rinterface._rinterface import *
ImportError: libicuuc.so.58: cannot open shared object file: No such file or directory

```

The rpy2 module is definitely installed, as can be seen with `conda list`, so I'm not sure what's going wrong. Any guidance on how to resolve this would be much appreciated. Thanks!

Output of conda list: 
```
# packages in environment at /home/lowa/miniconda3/envs/plasflow:
#
bioconductor-biocgenerics 0.22.0                 r3.3.2_0    bioconda
bioconductor-iranges      2.8.2                  r3.3.2_0    bioconda
bioconductor-s4vectors    0.12.2                 r3.3.2_0    bioconda
bioconductor-xvector      0.14.1                 r3.3.2_0    bioconda
bioconductor-zlibbioc     1.20.0                 r3.3.2_1    bioconda
biopython                 1.70                     py35_2    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.11.5                     0    conda-forge
cairo                     1.14.8                        0  
certifi                   2017.11.5                py35_0    conda-forge
curl                      7.55.1                        0    conda-forge
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
glib                      2.50.2                        1  
gsl                       2.1                           2    conda-forge
harfbuzz                  0.9.39                        2  
icu                       54.1                          0  
intel-openmp              2018.0.0             hc7b2577_8  
jpeg                      9b                            2    conda-forge
krb5                      1.14.2                        0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libpng                    1.6.34                        0    conda-forge
libssh2                   1.8.0                         2    conda-forge
libstdcxx-ng              7.2.0                h7a57d05_2  
libtiff                   4.0.9                         0    conda-forge
libxml2                   2.9.4                         0  
mkl                       2017.0.4             h4c4d0af_0  
mock                      2.0.0                    py35_0    conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.11.3                   py35_0  
openssl                   1.0.2n                        0    conda-forge
pandas                    0.22.0                   py35_0    conda-forge
pango                     1.40.3                        1  
pbr                       3.1.1                    py35_0    conda-forge
pcre                      8.39                          0    conda-forge
pip                       9.0.1                    py35_1    conda-forge
pixman                    0.34.0                        1    conda-forge
plasflow                  1.0.7                    py35_0    smaegol
protobuf                  3.5.1                    py35_3    conda-forge
python                    3.5.4                         2    conda-forge
python-dateutil           2.3                      py35_0    bioconda
pytz                      2017.3                     py_2    conda-forge
r-base                    3.3.2                         1  
readline                  6.2                           0    conda-forge
rpy2                      2.7.8              py35r3.3.2_1    bioconda
scikit-learn              0.18.1              np111py35_1  
scipy                     0.19.0              np111py35_0  
setuptools                38.4.0                   py35_0    conda-forge
six                       1.11.0                   py35_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tensorflow                0.10.0rc0           np111py35_0  
tk                        8.5.19                        2    conda-forge
wheel                     0.30.0                   py35_2    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by lowandrew** [comment]
Seems to be working as of today.

**Comment by feilongzh** [comment]
> Seems to be working as of today.
How to deal with that ?I have the same question.

**Comment by pablodz** [comment]
same here
