### ISSUE TITLE
ImportError: libicuuc.so.58: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lisa4109** [smaegol/PlasFlow#43]
I had install plasflow following the “Conda-based - recommended” by miniconda3.
command：
conda config --add channels bioconda
conda config --add channels conda-forge
conda create --name plasflow python=3.5
source activate plasflow
conda install -c jjhelmus tensorflow=0.10.0rc0
conda install plasflow -c smaegol

after all of the dependencies being installed, run
~/biosoft/miniconda3/envs/plasflow/bin/PlasFlow.py --input plasflow.test.fa --output W3

then, the erro occured like this:

`Traceback (most recent call last):
  File "/usr/lishasha/biosoft/miniconda3/envs/plasflow/bin/PlasFlow.py", line 50, in <module>
    from rpy2.robjects.packages import importr
  File "/usr/lishasha/biosoft/miniconda3/envs/plasflow/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/usr/lishasha/biosoft/miniconda3/envs/plasflow/lib/python3.5/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: libicuuc.so.58: cannot open shared object file: No such file or directory`

**Comment by feilongzh** [comment]
> I had install plasflow following the “Conda-based - recommended” by miniconda3. command： conda config --add channels bioconda conda config --add channels conda-forge conda create --name plasflow python=3.5 source activate plasflow conda install -c jjhelmus tensorflow=0.10.0rc0 conda install plasflow -c smaegol
> 
> after all of the dependencies being installed, run ~/biosoft/miniconda3/envs/plasflow/bin/PlasFlow.py --input plasflow.test.fa --output W3
> 
> then, the erro occured like this:
> 
> `Traceback (most recent call last): File "/usr/lishasha/biosoft/miniconda3/envs/plasflow/bin/PlasFlow.py", line 50, in <module> from rpy2.robjects.packages import importr File "/usr/lishasha/biosoft/miniconda3/envs/plasflow/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 16, in <module> import rpy2.rinterface as rinterface File "/usr/lishasha/biosoft/miniconda3/envs/plasflow/lib/python3.5/site-packages/rpy2/rinterface/__init__.py", line 92, in <module> from rpy2.rinterface._rinterface import (baseenv, ImportError: libicuuc.so.58: cannot open shared object file: No such file or directory`

I have the same question.

**Comment by CXang** [comment]
> 

i have the same question,could you tell me how to solve that~thanks

**Comment by CXang** [comment]
if you have the problem like this, the lack of libicuuc.so.58 is the reason, you could build soft link;
command: (if you use conda to download this software!)
cd /usr/anaconda/envs/plasflow_master/lib
ln -s /usr/anaconda/lib/libicuuc.so.58      libicuuc.so.58 
ln -s /usr/anaconda/lib/libicui18n.so.58   libicui18n.so.58  
ln -s /usr/anaconda/lib/libicudata.so.58   libicudata.so.58
then, run again,you will find it is OK !
hope to help you ~~~


Traceback (most recent call last): File "/usr/lishasha/biosoft/miniconda3/envs/plasflow/bin/PlasFlow.py", line 50, in <module> from rpy2.robjects.packages import importr File "/usr/lishasha/biosoft/miniconda3/envs/plasflow/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 16, in <module> import rpy2.rinterface as rinterface File "/usr/lishasha/biosoft/miniconda3/envs/plasflow/lib/python3.5/site-packages/rpy2/rinterface/__init__.py", line 92, in <module> from rpy2.rinterface._rinterface import (baseenv, ImportError: libicuuc.so.58: cannot open shared object file: No such file or directory

ImportError: libicuuc.so.58: cannot open shared object file: No such file or directory
ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
ImportError: libicudata.so.58: cannot open shared object file: No such file or directory

**Comment by pl19940314** [comment]
I have met similar problem ,how can I could solve it ?
Traceback (most recent call last):
  File "/home/meta/miniconda3/envs/plasflow/bin/PlasFlow.py", line 50, in <module>
    from rpy2.robjects.packages import importr
  File "/home/meta/miniconda3/envs/plasflow/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/home/meta/miniconda3/envs/plasflow/lib/python3.5/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: libicuuc.so.58: cannot open shared object file: No such file or directory
