### ISSUE TITLE
ImportError: cannot import name 'MafIO'

### ISSUE THREAD

**Issue by palomo11** [smaegol/PlasFlow#5]
Hi,

I'm running PlasFlow and I get the tsv file, but at some point it gets the following error:
```
Traceback (most recent call last):
  File "/home/people/alpal/.conda/envs/plasflow/bin/PlasFlow.py", line 375, in <module>
    "_chromosomes.fasta", "fasta")
  File "/home/people/alpal/.conda/envs/plasflow/lib/python3.5/site-packages/Bio/SeqIO/__init__.py", line 461, in write
    from Bio import AlignIO
  File "/home/people/alpal/.conda/envs/plasflow/lib/python3.5/site-packages/Bio/AlignIO/__init__.py", line 154, in <module>
    from . import MafIO
ImportError: cannot import name 'MafIO'
```
I have checked python and:

```
>>> import Bio 

>>> print(Bio.__version__)
1.69

>>> from Bio import AlignIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/people/alpal/.conda/envs/plasflow/lib/python3.5/site-packages/Bio/AlignIO/__init__.py", line 154, in <module>
    from . import MafIO
ImportError: cannot import name 'MafIO'

>>> from Bio.AlignIO import MafIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/people/alpal/.conda/envs/plasflow/lib/python3.5/site-packages/Bio/AlignIO/__init__.py", line 154, in <module>
    from . import MafIO
ImportError: cannot import name 'MafIO'
```

I installed PlasFlow using conda.

Any idea bout what is going on?

Thanks in advance.

**Comment by smaegol** [comment]
Did you try reinstalling? I think there is something wrong with your biopython installation. If new installation of PlasFlow doesn't fix the problem try to issue: 

`conda install biopython `

to upgrade to 1.70, and if it will not work try: 

`conda install biopython --update-deps`

 This problem, although strange for me, affects only the part of code in which fasta output files are generated, tsv with predictions should be generated in all cases.

Best,
Pawel

**Comment by palomo11** [comment]
Thanks! It works now.

**Comment by smaegol** [comment]
Great. Hope you will find PlasFlow useful.
